### ISSUE TITLE
Unable to unlock screen even with correct password

### ISSUE THREAD

**Issue by myandeg** [cutefishos/screenlocker#2]
**System**: ArchLinux (Updated)
**Version**: 0.4 (with package cutefish-screenlocker-0.4-1)

After locking the screen, I was trying to unlock it with the password. But it gives nothing but "Unlocking failure". The only thing I can do is to kill the corresponding PID to terminate the process.

This is the output when I ran this program in terminal.

![2021-08-27-152746_750x500_scrot](https://user-images.githubusercontent.com/43145549/131089968-36a90419-699d-454a-9362-0deb6f45f54a.png)

**Comment by wecli** [comment]
I also encountered the same problem. After the screen is locked, I cannot enter the system again after entering the correct password.

**Comment by myandeg** [comment]
> Same here, is this fixed in `0.5`? I think `0.4` is marked as outdated in arch packages.
> 
> > if not fixes yet, I think this issue should be labeled as critical

I have built and updated the packages to `0.5` from AUR Package Repositories. However, this bug remains the same.

**Comment by alizteralvord** [comment]
> > Same here, is this fixed in `0.5`? I think `0.4` is marked as outdated in arch packages.
> > > if not fixes yet, I think this issue should be labeled as critical
> 
> I have built and updated the packages to `0.5` from AUR Package Repositories. However, this bug remains the same.

`0.6` still same

**Comment by DanielVenturini** [comment]
I have the same issue running version `0.5` of `screenlocker` on arch linux. I have some clues that may help us to figure out the problem.

I cloned this repo and I built it, as described on [readme](https://github.com/cutefishos/screenlocker#build).
I realized where the authentication fails, even typing the correct password.

When using the default authentication method, the PAM one, ([defining HAVE_PAM](https://github.com/cutefishos/screenlocker/blob/main/config-unix.h.cmake#L2)), the authentication fails when calling to `pam_authenticate` method.

https://github.com/cutefishos/screenlocker/blob/55fb5253deeeb5bcab54daed3ce75f64396debb8/checkpass/checkpass_pam.c#L167-L174

I also realized that the source code is basically the same as the [kscreenlocker code](https://invent.kde.org/plasma/kscreenlocker/-/blob/master/kcheckpass/checkpass_pam.c#L167)

By the other hand, when using the shadow authentication method (defining HAVE_SHADOW), the authentication fails when getting `pw->pw_passwd` variable, which comes null.

https://github.com/cutefishos/screenlocker/blob/55fb5253deeeb5bcab54daed3ce75f64396debb8/checkpass/checkpass_shadow.c#L56-L57

On shadow method, the error may be happen due the lack of permission when getting the shadow file. I wasn't able to run the compiled `screenlocker` with super user, and Qt didn't let me to set setuid bit on this executable.

This is what I discovered about this error. I hope that someone helps us too.

**Comment by Ar7hurz1nh0** [comment]
I have good news! I was able to unlock with my password, and the solution is quite easy too!

As described in this [forum post](https://www.linuxquestions.org/questions/linux-enterprise-47/why-is-pam_authenticate-returning-authentication-failure-for-valid-user-passwd-333213/), what's causing the `Authentication Failure` is the configuration of the `other` PAM Module.

In my case it was simple as switch the `/etc/pam.d/other` to this:
```
#%PAM-1.0
auth      required   pam_unix.so
account   required   pam_unix.so
password  required   pam_unix.so
session   required   pam_unix.so
```
After this, launching `cutefish-screenlocker` and writing the user password should work! No reboot needed

**Disclosure**
I'm not a linux expert, although I didn't find anywhere that changing this file is dangerous, I could be wrong, do at your risk, or wait for others to confirm that it's safe

**Comment by DanielVenturini** [comment]
@Ar7hurz1nh0 That worked like a charm to me. Thanks a lot.

**Comment by aleOS2** [comment]
@Ar7hurz1nh0 It's worked for me too, thanks!

**Comment by NightRaidGamer** [comment]
auto login doesn't work can someone help me please? any temporary solution?

**Comment by Ar7hurz1nh0** [comment]
@NightRaidGamer is your problem is related to not being able to unlock with the right password?

**Comment by NightRaidGamer** [comment]
> @NightRaidGamer is your problem is related to not being able to unlock with the right password?

no, my problem is the auto login function doesn't work when i activate it..

**Comment by Ar7hurz1nh0** [comment]
@NightRaidGamer I dont know what do you mean with auto login, but I recommend you creating another issue here for better understanding

**Comment by felixonmars** [comment]
I probably have found the cause here. `cutefish-screenlocker` uses `KSCREENSAVER_PAM_SERVICE` which is `kde`, which corresponds to `/etc/pam.d/kde` and is only available in the plasma-workspace package. Since this is a rather large package set I don't think adding the dependency would be a good idea.

I have overridden the value in Arch Linux's cutefish-screenlocker 0.5-2. Please retry with the new version if you are still interested.

**Comment by joe733** [comment]
https://user-images.githubusercontent.com/38415384/190902943-fa3bd6ec-2f21-4862-9df1-b8ba6150535e.mp4

Tested on Arch. The issue seems resolved. Voting to close this issue.

**Comment by myandeg** [comment]
Thanks a lot for all your contributions.
